### PR TITLE
Add dropzone CSV file submit form and cleanup dashboard

### PR DESCRIPTION
**Pull request by kegilbert**
Removed extra dashboard items to just show the table and navbar which includes a drag'n'drop menu for submitting CSV files.

Sorry for the mass of files, the dropzone changes pulled in a ton of CSS changes that shouldn't matter much. Important changes are in:

- index.html
- submitData.html

### CODE REVIEW

**Comment by sarahmarshy** [comment]
Can you put back in the Arm logo in the corner? Not necessary, but I felt like it made the site look slightly more professional.

**Comment by kegilbert** [comment]
Good point, got a little hasty with the delete key.

**Comment by kegilbert** [comment]
@sarahmarshy Added the logo back in.

**Comment by sarahmarshy** [comment]
@kegilbert  -- one last comment actually, can you add instructions/sample data to the README?

**Pull request merged**
